### ISSUE TITLE
Bundle jQuery instead of using CDN

### ISSUE THREAD

**Issue by benjaoming** [sphinx-contrib/jquery#1]
There are a couple of things from [the proposal](https://github.com/readthedocs/readthedocs.org/pull/9665) that aren't implemented.

But I wanted to flag the usage of a CDN jQuery since it's currently implemented in a way that conflicts with the proposal.

**Comment by AA-Turner** [comment]
We should probably also include the compat module from Sphinx 5, for projects relying on the changes Sphinx made to global JS state.

A

**Comment by benjaoming** [comment]
@AA-Turner can you elaborate? I'm not familiar with the concept, is it the module listed here from 7 years ago?

https://www.npmjs.com/package/jquery-compat

**Comment by benjaoming** [comment]
It'd be great to have a release that's 1:1 with Sphinx 5.x and then do subsequent updates.

**Comment by AA-Turner** [comment]
https://github.com/sphinx-doc/sphinx/blob/v5.3.0/sphinx/themes/basic/static/_sphinx_javascript_frameworks_compat.js

**Comment by benjaoming** [comment]
Thanks! I will include it :+1: 

I understand from this quick explainer that it shouldn't be considered necessary moving forwards: https://www.oreilly.com/library/view/advancing-from-jquery/9781491963333/video255838.html

**Comment by AA-Turner** [comment]
Sorry, I don't understand your link. This compatability module factored out the patches Sphinx used to make to jQuery in doctools.js. I don't believe it has anything to do with the jQuery version?

A

**Comment by benjaoming** [comment]
Aaaaah okay, I got it confused with https://www.npmjs.com/package/jquery-compat

**Comment by benjaoming** [comment]
Can you say something about the relevance of `[_sphinx_javascript_frameworks_compat.js](https://github.com/sphinx-doc/sphinx/blob/v5.3.0/sphinx/themes/basic/static/_sphinx_javascript_frameworks_compat.js)` moving forwards?

**Comment by AA-Turner** [comment]
If extensions rely on the patches to jQuery defined within it, and we remove the patches to jQuery, the extensions will break.

A

**Comment by benjaoming** [comment]
I've added a 3.0.0 and 4.0.0 milestone to distinguish between the releases so we can have 1:1 Sphinx 5.x support and then move forwards after that.

**Comment by benjaoming** [comment]
Does that sound good?
