### ISSUE TITLE
Possibly rename jquery.js

### ISSUE THREAD

**Issue by benjaoming** [sphinx-contrib/jquery#10]
Originally a flyby comment:

> Maybe worth naming the actively included file as `jquery-3.6.0.min.js` because it should be aggressively cached? Hence, if the extension is upgraded with a new version of `jquery.js`, won't that be cached as well?

_Originally posted by @benjaoming in https://github.com/sphinx-contrib/jquery/issues/7#issuecomment-1292539209_

Is it possible that we rename jquery to something with its version string? Or will that cause issues with extensions/themes trying to predict its location?

**Comment by PRO-BROS** [comment]
Yep. I am also doing same with my [site](https://prhocoding.com/)

**Comment by AA-Turner** [comment]
It was included as `jquery.js` to match Sphinx's behaviour most closely. We could include both, or include a query-string with the version?

A

**Comment by benjaoming** [comment]
> or include a query-string with the version

That's an interesting concept! I'm wondering if that works though, for instance if local paths are generally okay with `file:///path/to/jquery.js?3.6.0` (tested and it works in practice)

> We could include both

I think that one is difficult, since they will both be loaded.

Since this is a new feature, maybe the best bet is to say: While we might theoretically benefit from this, the idea of this extension is just to bridge a gap in legacy behavior.

So perhaps there's no use in going through the scenarios until someone calls out broken behavior. Caches can be flushed, after all.. and I think even CF are removing security issues with jQuery from their caches.

**Comment by AA-Turner** [comment]
> Since this is a new feature, maybe the best bet is to say: While we might theoretically benefit from this, the idea of this extension is just to bridge a gap in legacy behavior.

This is fine with me, closing for now then (as 'not planned', as we've agreed this is out-of-scope).

A
