### ISSUE TITLE
Packaging `sphinxcontrib-jquery` for `conda-forge`

### ISSUE THREAD

**Issue by BSGalvan** [sphinx-contrib/jquery#11]
Hi!
I am currently in the process of packaging `sphinxcontrib-jquery` for `conda-forge`.
This is majorly because it is a dependency of another package on `conda-forge` which I currently maintain (`sphinx-hoverxref`), and not having this on `conda-forge` will cause the other to become stale.

I am raising this issue for three reasons.
First off, to notify the devs that such an alternative download channel will come into existence once a PR is merged. 
Secondly, it would be awesome if any developer(s) would sign on to be a co-maintainer of the `conda-forge` recipe. This would ensure more eyes and brains on the recipe itself, lowering the risk of it becoming stale as updates happen here.
Finally, in order to properly package this for `conda-forge`, from my understanding, the jQuery source also needs to have a separate licence file in the source tree. Possibly a file similar to `vendor_licences/licence` would fit the bill.

Please let me know your thoughts, and thanks for the software! 😄

**Comment by AA-Turner** [comment]
Happy to be listed.

> Finally, in order to properly package this for `conda-forge`, from my understanding, the jQuery source also needs to have a separate licence file in the source tree. Possibly a file similar to `vendor_licences/licence` would fit the bill.

Please can you confirm this?

A

**Comment by BSGalvan** [comment]
Awesome! I will add you to the list of maintainers then.

Regarding the confirmation, this is from the [current PR](https://github.com/conda-forge/staged-recipes/pull/20921)'s checklist:

> ... Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged).

**Comment by AA-Turner** [comment]
Does that mean Python packages, or any software library? I don't want to add unneeded things to the package, so if conda requires it please can you include it only in the conda package.

A

**Comment by AA-Turner** [comment]
Done, see https://github.com/conda-forge/sphinxcontrib-jquery-feedstock.

A
