### ISSUE TITLE
Published packages using incorrect filepaths

### ISSUE THREAD

**Issue by phlax** [sphinx-contrib/jquery#15]
The wheel packages built and published on pypi use a `.` for namespacing in the filename - yet when built with `flit` they produce packages that use `_` 

This is important because `pypa/installer` uses the wheel filename to ascertain the paths of files inside

With the current setup sphinxcontrib-jquery is uninstallable by anything that uses `pypa/installer` (eg bazels `rules_python`) - and i suspect that some spec is broken somewhere

**Comment by AA-Turner** [comment]
I have tested [version 4](https://pypi.org/project/sphinxcontrib-jquery/4.0/) with `python -m installer` and it seems to work.

A
