### ISSUE TITLE
Explicit dependency on Sphinx?

### ISSUE THREAD

**Issue by befeleme** [sphinx-contrib/jquery#19]
Hi,
I package this extension to Fedora and got a question regarding the dependency on Sphinx. I looked at the other sphinxcontrib extensions and it seems all of them explicitly require Sphinx (via install_requires or similar package interfaces). `jquery` however not, although it clearly has no use without Sphinx in the environment. Should it be added to dependencies? Thank you.

**Comment by AA-Turner** [comment]
Done.

A
