### ISSUE TITLE
Integrity check seems to fail in browser

### ISSUE THREAD

**Issue by kreuzberger** [sphinx-contrib/jquery#20]
Using it with Sphinx > 6.0 failed cause the provided integrity check does not work.
Removing the integrity attribute fixed the issue.

Maybe
a) a conf option to add integrity or not
b) update the sha384 sum? 

This is the output of the sha384sum of jquery.js file that is in the html output directoy.
```
sha384sum jquery.js 
bed5d131ede61826ce798ee5df468883c1fda7719d7927b820594fe86f0931aee8ee55ef9f3dc614accfc7325d3df18a  jquery.js
```

**Comment by kreuzberger** [comment]
openssl dgst -sha384 -binary jquery.js | openssl base64 gives the same sha384 key

**Comment by AA-Turner** [comment]
```bash
$ sha384sum jquery.js
bed5d131ede61826ce798ee5df468883c1fda7719d7927b820594fe86f0931aee8ee55ef9f3dc614accfc7325d3df18a  jquery.js
$ openssl dgst -sha384 -hex jquery.js
SHA2-384(jquery.js)= bed5d131ede61826ce798ee5df468883c1fda7719d7927b820594fe86f0931aee8ee55ef9f3dc614accfc7325d3df18a
$ openssl dgst -sha384 -binary jquery.js | openssl base64
vtXRMe3mGCbOeY7l30aIg8H9p3GdeSe4IFlP6G8JMa7o7lXvnz3GFKzPxzJdPfGK
```

Output starting ``bed5...`` is the hexadecimal output (also reported by ``sha384sum``); starting ``vtXR...`` is the base64 output. Are you loading the documentation from a ``file://`` URI?

A

**Comment by AA-Turner** [comment]
Closing, as I believe the SHA 384 checksums to be correct.

A

**Comment by kreuzberger** [comment]
Sorry for not replying to the question. You were right, the checksums were correct! I didnt realise the base64 encoding.
