### ISSUE TITLE
Could not import extension sphinxcontrib.jquery (exception: No module named 'sphinxcontrib')

### ISSUE THREAD

**Issue by ghtmtt** [sphinx-contrib/jquery#21]
Hi,

I've a sphinx project with a virtual environment. After installing via pip `sphinxcontrib.jquery` and after having edited the `conf.py` file:

```python
extensions = [
    'sphinx_copybutton',
    'sphinxcontrib.jquery'
]
```

when compiling the documentation I always get the following error:

```bash
make html
Running Sphinx v5.3.0
loading translations [it]... done

Extension error:
Could not import extension sphinxcontrib.jquery (exception: No module named 'sphinxcontrib')
make: *** [Makefile:19: html] Error 2
```

Without specifying the extension in the `conf.py` folder, the html is correctly created.

**Comment by AA-Turner** [comment]
Please try version 4 (`pip install "sphinxcontrib-jquery==4.0"`) and open a new issue if it continues to fail.

A
