### ISSUE TITLE
Confirm implementation with another extension

### ISSUE THREAD

**Issue by benjaoming** [sphinx-contrib/jquery#6]
Proposing to cross-reference this issue with some other extension that starts using and automatically testing the inclusion of this extension.

sphinx_rtd_theme is a good candidate :+1:

**Comment by benjaoming** [comment]
https://github.com/readthedocs/sphinx-hoverxref/pull/241

**Comment by AA-Turner** [comment]
Linked PR merged.

A

**Comment by benjaoming** [comment]
The implementation with sphinx-hoverxref shows that we are compatible with a Sphinx 5.x extension.

I'm waiting for updates of https://github.com/readthedocs/sphinx_rtd_theme/ to trickle down, that way we can also prove simultaneous Sphinx 5 & 6 compatibility.

@agjohnson one of the priorities for Sphinx 6.x compatibility + docutils 0.18 would be to have a release ready soon enough for testing sphinxcontrib-jquery. So I think our timeframe should be to get 1.2 out <2 weeks after 1.1, otherwise we don't have much buffer to discover and fix issues. That's in case Sphinx 6 is released on Dec 1.

**Comment by benjaoming** [comment]
But we don't need the issue to track this, it's great that the first extension showed no issues :+1:
